version: "3.9"

services:
  db:
    container_name: "mydb1"
    image: "mysql:latest"
    networks:
      - deep_net
    volumes:
      -  /data:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=redhat
      - MYSQL_DATABASE=mydb
      - MYSQL_USER=deepak
      - MYSQL_PASSWORD=redhat

  wp:
    depends_on:
      - db
    container_name: "mywp"
    image: "wordpress:latest"
    networks:
      - deep_net
    ports:
      - 8080:80
    environment:
      WORDPRESS_DB_HOST: mydb1
      WORDPRESS_DB_USER: deepak
      WORDPRESS_DB_PASSWORD: redhat
      WORDPRESS_DB_NAME: mydb
    volumes:
      - /wordpress:/var/www/html

networks:
  deep_net:
    driver: bridge
    ipam:
      config:
        - subnet: 172.16.238.0/24
